### ISSUE TITLE
Server crashing upon generation

### ISSUE THREAD

**Issue by ElegantFx** [NomeQ/open-gtfs-map#2]
When trying to generate a map from the link "http://data.trilliumtransit.com/gtfs/mendocino-ca-us/mendocino-ca-us.zip" this error (that makes the server crash shows up):
`                for (var i = 0; i < best_trip.length; i++) {
                                              ^

TypeError: Cannot read property 'length' of undefined
    at drawShapes (C:\Users\tobia\Documents\gtfs\maps\mapmaker.js:144:33)
    at C:\Users\tobia\Documents\gtfs\maps\mapmaker.js:131:4
    at Parser.<anonymous> (C:\Users\tobia\Documents\gtfs\node_modules\csv-parse\lib\index.js:71:16)
    at Parser.emit (events.js:223:5)
    at endReadableNT (_stream_readable.js:1185:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! open-gtfs-map@0.0.1 start: "node ./bin/www"
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the open-gtfs-map@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

Is it me or is there something wrong with the app?

**Comment by NomeQ** [comment]
Apologies on the slow reply! This is a project I started as a class project while I was in school. I haven't looked at it in a while, but it is currently abandoned code, so I would not be surprised if it is broken.
